#ifndef YSQL_COMMANDS_H_INCLUDED
#define YSQL_COMMANDS_H_INCLUDED

#define COMMAND_GET "GET" // GET <KEY>
#define COMMAND_SET "SET" // SET <KEY> <VALUE>
#define COMMAND_GET_KEYS "GET_KEYS" // GET_KEYS 
#define COMMAND_GET_KEYS_PREFIX "GET_KEYS_PREFIX" // GET_KEYS_PREFIX <PREFIX> 
#define COMMAND_GET_FF "GET_FF" // GET_FF <KEY>
#define COMMAND_GET_FB "GET_FB" // GET_FB <KEY>
#define COMMAND_REMOVE "REMOVE" // REMOVE <KEY>

#endif // YSQL_COMMANDS_H_INCLUDED