COMMAND_LENGTH_COMMAND_MESSAGE = 2 
COMMAND_LENGTH_KEY_LENGTH = 2
COMMAND_LENGTH_TOTAL_MESSAGE = 8 
COMMAND_LENGTH_VALUE_LENGTH = 4
COMMAND_LENGTH_NUM_ELEMENTS = 8
COMMAND_LENGTH_CURSOR_PADDING = 6
COMMAND_LENGTH_CURSOR_SIZE = 2