COMMAND_CODE_OK = 0
COMMAND_CODE_ERR = 1
COMMAND_CODE_GET = 2
COMMAND_CODE_SET = 3
COMMAND_CODE_GET_KEYS = 4
COMMAND_CODE_GET_KEYS_PREFIX = 5
COMMAND_CODE_GET_FF = 6
COMMAND_CODE_GET_FB = 7
COMMAND_CODE_REMOVE = 8
COMMAND_CODE_DATA_NOT_FOUND = 9
INVALID_COMMAND_CODE = 10

COMMAND_LENGTH_TOTAL_MESSAGE = 8
COMMAND_LENGTH_NUM_ELEMENTS = 8
COMMAND_LENGTH_COMMAND_MESSAGE = 2
COMMAND_LENGTH_KEY_LENGTH = 2
COMMAND_LENGTH_VALUE_LENGTH = 4

